name: Deploy to Staging Server
on:
  push:
    branches: [stage]

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST_STAGING}}
          key: ${{secrets.SSH_KEY_STAGING}}
          username:
            ${{ secrets.SSH_USERNAME_STAGING}}
            # password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 200m
          script: |
            cd /home/ubuntu
            sudo systemctl stop nginx
            sudo rm -r -f client
            git clone git@github.com:BongoHive/ags-dashboard-frontend.git client 
            cd client
            git checkout stage
            yarn install
            export NODE_OPTIONS=--max_old_space_size=8192
            yarn add env-cmd
            yarn stage
            echo "Built react application"
            sudo systemctl restart nginx
            sudo systemctl status nginx
            exit
